{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "visionone-bank-demo.fullname" . }}
  labels:
    {{- include "visionone-bank-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  TMV1_API_KEY: {{ .Values.secrets.tmv1ApiKey | quote }}
  FILE_SECURITY_API_KEY: {{ .Values.secrets.fileSecurityApiKey | quote }}
  LLM_API_KEY: {{ .Values.secrets.llmApiKey | quote }}
  AI_SCANNER_TARGET_TOKEN: {{ .Values.secrets.aiScannerTargetToken | quote }}
{{- end }}
